version: '3.8'

volumes:
  geekShoppingDB:

networks:
  geekShoppingNET:

services:

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: geekShoppingDB
    ports:
      - "1433:1433"
    volumes:
      - geekShoppingDB:/var/lib/sqlserver
    networks:
      - geekShoppingNET
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: numsey#2021
      MSSQL_PID: EXPRESS